# .github/workflows/ci.yml
name: Python tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: pytest -q
